export const siteConfig = {
  name: "Tamem J",
  domain: "tamemj.com",
  url: "https://tamemj.com",
  email: "hello@tamemj.com",
  supportEmail: "support@tamemj.com",
  title: "Tamem J | iOS App Developer",
  description:
    "Independent iOS developer creating simple, beautiful iPhone apps with a focus on clean design and useful everyday tools.",
  tagline: "Designing Simple, Beautiful iOS Apps"
} as const;

export const seoKeywords = [
  "iOS apps",
  "iPhone apps",
  "indie app developer",
  "iOS developer portfolio",
  "mobile app developer",
  "app store developer",
  "app support portal",
  "enterprise IT support guides",
  "corporate tech fixes",
  "service catalog demo",
  "IT troubleshooting documentation",
  "GitHub releases downloads",
  "free software downloads",
  "macOS app downloads",
  "Windows app downloads",
  "Linux app downloads",
  "code editor downloads",
  "developer tools",
  "networking tools downloads",
  "media tools downloads",
  "design tools downloads",
  "developer tool downloads",
  "notion download",
  "cursor editor download",
  "visual studio code download",
  "Microsoft Adobe Figma troubleshooting",
  "Intune support",
  "Microsoft Entra troubleshooting",
  "Jamf troubleshooting",
  "Kandji troubleshooting",
  "Okta support docs",
  "enterprise knowledge base articles",
  "it support portal",
  "incident intake form",
  "service catalog",
  "knowledge base",
  "pc build guides",
  "pc part picker guidance",
  "indie iOS developer",
  "tamemj.com"
];
