import type { Ticket } from "@/types/support";

export const supportTicketEmailRecipient =
  process.env.NEXT_PUBLIC_SUPPORT_TICKET_EMAIL_TO?.trim() || "noreply@tamemj.com";

export const supportTicketEmailEndpoint =
  process.env.NEXT_PUBLIC_SUPPORT_TICKET_EMAIL_ENDPOINT?.trim() || "";

function stringifyRequestedField(value: string | string[] | boolean): string {
  if (Array.isArray(value)) {
    return value.join(", ");
  }

  if (typeof value === "boolean") {
    return value ? "Yes" : "No";
  }

  return value;
}

export function buildSupportTicketEmailMessage(ticket: Ticket): {
  to: string;
  subject: string;
  text: string;
} {
  const subject = `[${ticket.id}] ${ticket.type} ${ticket.priority} - ${ticket.summary}`;

  const lines: string[] = [
    `Ticket ID: ${ticket.id}`,
    `Type: ${ticket.type}`,
    `Status: ${ticket.status}`,
    `Priority: ${ticket.priority}`,
    `Impact/Urgency: ${ticket.impact}/${ticket.urgency}`,
    `Requester Name: ${ticket.requesterName}`,
    `Requester Email: ${ticket.requesterEmail}`,
    `Requester Phone: ${ticket.requesterPhone}`,
    `Category: ${ticket.category}`,
    `Subcategory: ${ticket.subcategory ?? "N/A"}`,
    `Product: ${ticket.product}`,
    `Preferred Contact: ${ticket.preferredContactMethod}`,
    `Created At: ${new Date(ticket.createdAt).toISOString()}`,
    "",
    "Summary:",
    ticket.summary,
    "",
    "Description:",
    ticket.description,
    ""
  ];

  if (ticket.attachments.length > 0) {
    lines.push("Attachment Filenames:");
    lines.push(...ticket.attachments.map((name) => `- ${name}`));
    lines.push("");
  }

  if (ticket.requestedFields && Object.keys(ticket.requestedFields).length > 0) {
    lines.push("Requested Fields:");
    for (const [key, value] of Object.entries(ticket.requestedFields)) {
      lines.push(`- ${key}: ${stringifyRequestedField(value)}`);
    }
    lines.push("");
  }

  lines.push("Generated by tamemj.com Support Portal ticket submission flow.");

  return {
    to: supportTicketEmailRecipient,
    subject,
    text: lines.join("\n")
  };
}

export interface SendSupportTicketEmailResult {
  ok: boolean;
  message: string;
}

export async function sendSupportTicketEmail(
  ticket: Ticket,
  options?: { turnstileToken?: string | null }
): Promise<SendSupportTicketEmailResult> {
  if (!supportTicketEmailEndpoint) {
    return {
      ok: false,
      message: "Support email endpoint is not configured. Set NEXT_PUBLIC_SUPPORT_TICKET_EMAIL_ENDPOINT."
    };
  }

  const turnstileToken = options?.turnstileToken?.trim() ?? "";
  if (!turnstileToken) {
    return {
      ok: false,
      message: "Security verification is required before sending ticket email."
    };
  }

  const email = buildSupportTicketEmailMessage(ticket);

  try {
    const response = await fetch(supportTicketEmailEndpoint, {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        source: "support-portal",
        ticket,
        email,
        turnstileToken
      })
    });

    if (!response.ok) {
      let details = "";

      try {
        const data = (await response.json()) as { error?: string };
        details = data.error ? ` ${data.error}` : "";
      } catch {
        // no-op
      }

      return {
        ok: false,
        message: `Email service responded with ${response.status}.${details}`.trim()
      };
    }

    return {
      ok: true,
      message: `Ticket email sent to ${email.to}.`
    };
  } catch {
    return {
      ok: false,
      message: "Unable to reach support email service endpoint."
    };
  }
}
